/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FormalSpecificationsAnalysis;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        LibraryTest classUnderTest = new LibraryTest();
        //assertTrue(classUnderTest.someLibraryMethodReturnsTrue(), "someLibraryMethod should return 'true'");
    }
}
